services:
  - type: web
    name: healthfraudmlchain
    runtime: python
    region: oregon
    rootDir: HealthFraudMLChain

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn main:app

    healthCheckPath: /

    envVars:
      - key: FLASK_ENV
        value: production

      - key: SECRET_KEY
        generateValue: true

      - key: MONGODB_URI
        sync: false